name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:   # habilita botão "Run workflow"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npx playwright test



     
